compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  html-minifier-terser@*:
    dependencies:
      acorn: ^8.6.0
  terser-webpack-plugin@*:
    dependencies:
      acorn: ^8.6.0

yarnPath: .yarn/releases/yarn-4.0.1.cjs
