// import type {UnprocessedSidebars} from '@docusaurus/plugin-content-docs/lib/types';

function autoCategory(dirName: string, label = dirName) {
  return {
    type: 'category',
    label,
    items: [
      {
        type: 'autogenerated',
        dirName,
      },
    ],
  };
}

// TODO: Sidebar type is not working well
const sidebar = {
  docs: [
    'about',
    {
      type: 'category',
      label: 'Weixin official account',
      collapsible: false,
      items: [
        autoCategory('Science'),
        autoCategory('Technology'),
        autoCategory('Humanities'),
        autoCategory('Stories', 'Short stories'),
      ],
    },
    {
      type: 'category',
      label: 'Zhihu',
      collapsible: false,
      items: [autoCategory('Digital', 'Digital circuit notes'), autoCategory('LaTeX')],
    },
  ],
};

export = sidebar;
