const autoCategory = (dirName, label = dirName) => {
  return {
    type: "category",
    label,
    items: [
      {
        type: "autogenerated",
        dirName,
      },
    ],
  };
};

module.exports = {
  docs: [
    "about",
    {
      type: "category",
      label: "Weixin official account",
      collapsible: false,
      items: [
        autoCategory("Science"),
        autoCategory("Technology"),
        autoCategory("Humanities"),
        autoCategory("Stories", "Short stories"),
      ],
    },
    {
      type: "category",
      label: "Zhihu",
      collapsible: false,
      items: [
        autoCategory("Digital", "Digital circuit notes"),
        autoCategory("LaTeX"),
      ],
    }
  ],
};
