module.exports = {
  docs: {
    About: ["about", "Technology/docusaurus"],
    "Weixin official account": [
      {
        Science: [
          "Science/cavalieri",
          "Science/le-chatlier",
          "Science/derivative",
          "Science/marathon",
          "Science/circular",
          "Science/bee",
          "Science/electromagnetic",
          "Science/gfp",
          "Science/summation",
          "Science/resonance",
          "Science/dna",
          "Science/airy",
          "Science/ladder",
          "Science/amino-acid",
          "Science/vitamin",
        ],
        Technology: [
          "Technology/xor",
          "Technology/typeset",
          "Technology/scripting",
          "Technology/easy-tsims",
          "Technology/curve",
        ],
        Humanities: [
          {
            type: "autogenerated",
            dirName: "Humanities",
          },
        ],
        "Short stories": [
          {
            type: "autogenerated",
            dirName: "Stories",
          },
        ],
      },
    ],
    Zhihu: [
      {
        "Digital circuit notes": [
          {
            type: "autogenerated",
            dirName: "Digital",
          },
        ],
        LaTeX: ["LaTeX/circuitikz"],
      },
    ],
  },
};
